### ISSUE TITLE
repr="classic" + "inherit" generates broken code in BuckleScript

### ISSUE THREAD

**Issue by jchavarri** [ahrefs/atd#212] opened 2020-05-25 16:39 UTC
Example:

```
type b = [
  | Z
] <ocaml repr="classic">

type a = [
  | inherit b
  | X
] <ocaml repr="classic">
```

Generated code does not compile with BuckleScript:

```
Error: The implementation src/foo_bs.ml
       does not match the interface src/foo_bs-Client.cmi:
       Values do not match:
         val read_b : a Atdgen_codec_runtime.Decode.t
       is not included in
         val read_b : b Atdgen_codec_runtime.Decode.t
 ```

The generated code is:

```ocaml
let read_b = (
  Atdgen_codec_runtime.Decode.enum
  [
      (
      "Z"
      ,
        `Single (Z)
      )
  ]
)
```

but it should be something like:
```ocaml
let read_b = (
  Atdgen_codec_runtime.Decode.enum
  [
      (
      "Z"
      ,
        `Single ((Z: b))
      )
  ]
)
```

**Comment by cyberhuman** [comment] 2020-05-26 00:34
Duplicate of #154

**Closed by cyberhuman** 2020-05-26 00:34 UTC
