### ISSUE TITLE
atdgen: "Unbound value write__2" when declaring types in a specific order

### ISSUE THREAD

**Issue by Champitoad** [ahrefs/atd#308] opened 2022-07-14 13:51 UTC
I am having a very weird error, which I assume is a bug. The following file `logic.atd` works fine:

```
(* [...] Some preliminary definitions for `type_`, `expr`, etc *)

type action = [
  | AId
  | ADef of ((type_ * expr option) * uid)
  | AIntro of (int * (expr * type_) option)
  | AElim of uid
  | ACut of (form * uid)
  | AAssume of (form * uid)
  | AGeneralize of uid
  | AMove of (uid * uid option)
  | ADuplicate of uid
  | ALink of (ipath * ipath * itrace)
]

type env = {
  env_prp     : (name * arity            ) list;
  env_fun     : (name * sig_             ) list;
  env_var     : (name * bvar  list       ) list;
  env_tvar    : (name * type_ option list) list;
  env_evar    : (name * type_ list       ) list;
  env_handles : (vname * uid             ) list;
}

type atree = [
  | PLeaf
  | PNode of (action * atree list)
]
```

However if I swap the order of definitions of `env` and `action`, I get an error when compiling the Biniou helpers `logic_b.ml` (the same is true for JSON):

```
File "lib/api/logic_b.ml", line 608, characters 16-24:
608 |                 write__2
                      ^^^^^^^^
Error: Unbound value write__2
Hint: Did you mean write__3 or write__5?
```

If I either:
- remove the last definition `atree`;
- generate only the type definitions `logic_t.ml`;

then it compiles fine. Any idea what might cause this?

Here is the complete file:

```
(* -------------------------------------------------------------------- *)
(** Identifiers *)

type name = string
type vname = (name * int)

type uid = int

(* -------------------------------------------------------------------- *)
(** Types *)

type type_ = [
  | TVar of vname
  | TUnit
  | TProd of (type_ * type_)
  | TOr of (type_ * type_)
  | TRec of (name * type_)
]

type arity = type_ list
type sig_  = (arity * type_)

(* -------------------------------------------------------------------- *)
(** Expressions *)

type expr = [
  | EVar of vname
  | EFun of (name * expr list)
]

(* -------------------------------------------------------------------- *)
(** Formulas *)

type logcon = [ And | Or | Imp | Equiv | Not ]
type bkind  = [ Forall | Exist ]

type form = [
  | FTrue
  | FFalse
  | FPred of (name * expr list)
  | FConn of (logcon * form list)
  | FBind of (bkind * name * type_ * form)
]

(* -------------------------------------------------------------------- *)
(** Terms = Formulas + Expressions *)

type term = [F of form | E of expr]

(* -------------------------------------------------------------------- *)
(** Environments *)

type bvar = (type_ * expr option)

(* -------------------------------------------------------------------- *)
(** Actions *)

type pkind = [Hyp | Concl | Var of [Head | Body]]
type ctxt = { kind : pkind; handle : uid }
type ipath = { root : uid; ctxt : ctxt; sub : int list }

type choice = (int * expr option)
type itrace = choice list

type env = {
  env_prp     : (name * arity            ) list;
  env_fun     : (name * sig_             ) list;
  env_var     : (name * bvar  list       ) list;
  env_tvar    : (name * type_ option list) list;
  env_evar    : (name * type_ list       ) list;
  env_handles : (vname * uid             ) list;
}

type action = [
  | AId
  | ADef of ((type_ * expr option) * uid)
  | AIntro of (int * (expr * type_) option)
  | AElim of uid
  | ACut of (form * uid)
  | AAssume of (form * uid)
  | AGeneralize of uid
  | AMove of (uid * uid option)
  | ADuplicate of uid
  | ALink of (ipath * ipath * itrace)
]

type atree = [
  | PLeaf
  | PNode of (action * atree list)
]
```

**Comment by mjambon** [comment] 2022-11-14 19:49
I suspect this due to the, um, exotic implementation of detection of strongly-connected components and topological sort used to sort and group mutually-recursive type definitions. Using https://github.com/dmbaturin/ocaml-tsort/blob/master/src/lib/tsort.mli would solve this problem if it's confirmed.

Sorry for the delay in responding. If someone wants to fix this, please go for it.

**Comment by tysg** [comment] 2023-05-05 09:45
I can't seem to reproduce this with the latest `atdgen.2.11.0`. Notably, `atdgen -b` produces the same `logic_b.ml` file before and after swapping `env` and `action` in the given example. 

@Champitoad are you still facing this issue?

**Comment by Champitoad** [comment] 2023-05-05 11:56
Indeed @tysg after upgrading from 2.10.0 to 2.11.0 the issue disappears! Should I close the issue?

**Comment by tysg** [comment] 2023-05-07 05:16
@Champitoad I'm not a maintainer of this project but I believe it's reasonable to :)

**Comment by mjambon** [comment] 2023-05-09 02:54
ok, let's close this ticket. I'll open a new one specifically about replacing the tsort implementation.

**Closed by mjambon** 2023-05-09 02:54 UTC
Labels: bug, help wanted
